/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/skull.glb -o src/components/Skull.jsx -r public -k 
Skull by Quaternius
*/

import { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import { useExplode } from "../hooks/useExplode";

export function Skull(props) {
  const { nodes, materials } = useGLTF("/models/skull.glb");
  const group = useRef();

  const { heart } = useControls({
    bluebirddistance: {
      value: 2.4,
      min: 0,
      max: 10,
    },
  });
  useExplode(group, {
    distance: heart,
    rotationEnabled: true,
  });
  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="Skull_cell"
        geometry={nodes.Skull_cell.geometry}
        material={materials.Bone}
        position={[0.384, 1.124, 0.98]}
      />
      <mesh
        name="Skull_cell001"
        geometry={nodes.Skull_cell001.geometry}
        material={materials.Bone}
        position={[-0.013, -2.37, 1.795]}
      />
      <mesh
        name="Skull_cell002"
        geometry={nodes.Skull_cell002.geometry}
        material={materials.Bone}
        position={[-0.518, -2.227, 1.635]}
      />
      <mesh
        name="Skull_cell003"
        geometry={nodes.Skull_cell003.geometry}
        material={materials.Bone}
        position={[1.519, -0.023, 1.562]}
      />
      <mesh
        name="Skull_cell004"
        geometry={nodes.Skull_cell004.geometry}
        material={materials.Bone}
        position={[-1.074, 1.58, -1.545]}
      />
      <mesh
        name="Skull_cell005"
        geometry={nodes.Skull_cell005.geometry}
        material={materials.Bone}
        position={[-1.09, -2.079, 0.571]}
      />
      <mesh
        name="Skull_cell006"
        geometry={nodes.Skull_cell006.geometry}
        material={materials.Bone}
        position={[-1.458, -0.236, 1.669]}
      />
      <mesh
        name="Skull_cell007"
        geometry={nodes.Skull_cell007.geometry}
        material={materials.Bone}
        position={[-0.572, 0.018, -0.272]}
      />
      <mesh
        name="Skull_cell009"
        geometry={nodes.Skull_cell009.geometry}
        material={materials.Bone}
        position={[0.023, -0.208, 2.181]}
      />
      <mesh
        name="Skull_cell010"
        geometry={nodes.Skull_cell010.geometry}
        material={materials.Bone}
        position={[1.374, 0.194, -1.391]}
      />
      <mesh
        name="Skull_cell011"
        geometry={nodes.Skull_cell011.geometry}
        material={materials.Bone}
        position={[0.902, 2.327, -0.575]}
      />
      <mesh
        name="Skull_cell012"
        geometry={nodes.Skull_cell012.geometry}
        material={materials.Bone}
        position={[-1.884, -0.406, 0.949]}
      />
      <mesh
        name="Skull_cell013"
        geometry={nodes.Skull_cell013.geometry}
        material={materials.Bone}
        position={[0.034, 2.314, -0.789]}
      />
      <mesh
        name="Skull_cell014"
        geometry={nodes.Skull_cell014.geometry}
        material={materials.Bone}
        position={[0.054, 0.329, 2.112]}
      />
      <mesh
        name="Skull_cell015"
        geometry={nodes.Skull_cell015.geometry}
        material={materials.Bone}
        position={[-0.992, 2.137, 1.161]}
      />
      <mesh
        name="Skull_cell016"
        geometry={nodes.Skull_cell016.geometry}
        material={materials.Bone}
        position={[0.02, -2.895, 1.855]}
      />
      <mesh
        name="Skull_cell017"
        geometry={nodes.Skull_cell017.geometry}
        material={materials.Bone}
        position={[-0.596, -2.625, 1.515]}
      />
      <mesh
        name="Skull_cell018"
        geometry={nodes.Skull_cell018.geometry}
        material={materials.Bone}
        position={[0.566, -2.65, 1.536]}
      />
      <mesh
        name="Skull_cell019"
        geometry={nodes.Skull_cell019.geometry}
        material={materials.Bone}
        position={[-0.1, 1.932, -1.156]}
      />
      <mesh
        name="Skull_cell020"
        geometry={nodes.Skull_cell020.geometry}
        material={materials.Bone}
        position={[1.513, 1.086, 1.633]}
      />
      <mesh
        name="Skull_cell021"
        geometry={nodes.Skull_cell021.geometry}
        material={materials.Bone}
        position={[-1.781, 0.579, -0.705]}
      />
      <mesh
        name="Skull_cell022"
        geometry={nodes.Skull_cell022.geometry}
        material={materials.Bone}
        position={[2.062, 0.853, 0.678]}
      />
      <mesh
        name="Skull_cell023"
        geometry={nodes.Skull_cell023.geometry}
        material={materials.Bone}
        position={[0.561, 0.169, -0.662]}
      />
      <mesh
        name="Skull_cell024"
        geometry={nodes.Skull_cell024.geometry}
        material={materials.Bone}
        position={[1.138, -2.073, 0.527]}
      />
      <mesh
        name="Skull_cell025"
        geometry={nodes.Skull_cell025.geometry}
        material={materials.Bone}
        position={[-0.868, 2.465, 0.037]}
      />
      <mesh
        name="Skull_cell026"
        geometry={nodes.Skull_cell026.geometry}
        material={materials.Bone}
        position={[0.132, 2.295, 1.353]}
      />
      <mesh
        name="Skull_cell027"
        geometry={nodes.Skull_cell027.geometry}
        material={materials.Bone}
        position={[-1.105, -1.006, 1.856]}
      />
      <mesh
        name="Skull_cell028"
        geometry={nodes.Skull_cell028.geometry}
        material={materials.Bone}
        position={[-1.685, -0.918, 1.085]}
      />
      <mesh
        name="Skull_cell029"
        geometry={nodes.Skull_cell029.geometry}
        material={materials.Bone}
        position={[0.455, 0.203, 1.467]}
      />
      <mesh
        name="Skull_cell030"
        geometry={nodes.Skull_cell030.geometry}
        material={materials.Bone}
        position={[-1.291, 1.597, -0.943]}
      />
      <mesh
        name="Skull_cell031"
        geometry={nodes.Skull_cell031.geometry}
        material={materials.Bone}
        position={[-1.132, -1.667, -0.133]}
      />
      <mesh
        name="Skull_cell032"
        geometry={nodes.Skull_cell032.geometry}
        material={materials.Bone}
        position={[0.16, 1.129, -1.811]}
      />
      <mesh
        name="Skull_cell033"
        geometry={nodes.Skull_cell033.geometry}
        material={materials.Bone}
        position={[0.063, 2.571, -0.199]}
      />
      <mesh
        name="Skull_cell035"
        geometry={nodes.Skull_cell035.geometry}
        material={materials.Bone}
        position={[-1.218, -1.078, 0.93]}
      />
      <mesh
        name="Skull_cell036"
        geometry={nodes.Skull_cell036.geometry}
        material={materials.Bone}
        position={[1.815, 0.042, 0.003]}
      />
      <mesh
        name="Skull_cell037"
        geometry={nodes.Skull_cell037.geometry}
        material={materials.Bone}
        position={[1.526, -0.704, 1.608]}
      />
      <mesh
        name="Skull_cell038"
        geometry={nodes.Skull_cell038.geometry}
        material={materials.Bone}
        position={[0.46, -2.192, 1.568]}
      />
      <mesh
        name="Skull_cell039"
        geometry={nodes.Skull_cell039.geometry}
        material={materials.Bone}
        position={[-1.511, 2.36, -0.592]}
      />
      <mesh
        name="Skull_cell040"
        geometry={nodes.Skull_cell040.geometry}
        material={materials.Bone}
        position={[-0.7, -1.579, 1.554]}
      />
      <mesh
        name="Skull_cell041"
        geometry={nodes.Skull_cell041.geometry}
        material={materials.Bone}
        position={[0.792, -0.362, 1.16]}
      />
      <mesh
        name="Skull_cell042"
        geometry={nodes.Skull_cell042.geometry}
        material={materials.Bone}
        position={[-0.57, -0.075, 1.414]}
      />
      <mesh
        name="Skull_cell043"
        geometry={nodes.Skull_cell043.geometry}
        material={materials.Bone}
        position={[-0.82, 2.314, -0.868]}
      />
      <mesh
        name="Skull_cell044"
        geometry={nodes.Skull_cell044.geometry}
        material={materials.Bone}
        position={[0.815, 2.203, -1.285]}
      />
      <mesh
        name="Skull_cell045"
        geometry={nodes.Skull_cell045.geometry}
        material={materials.Bone}
        position={[0.633, -0.596, 1.923]}
      />
      <mesh
        name="Skull_cell046"
        geometry={nodes.Skull_cell046.geometry}
        material={materials.Bone}
        position={[-0.244, -1.151, 2.069]}
      />
      <mesh
        name="Skull_cell047"
        geometry={nodes.Skull_cell047.geometry}
        material={materials.Bone}
        position={[1.206, 2.285, 0.958]}
      />
      <mesh
        name="Skull_cell048"
        geometry={nodes.Skull_cell048.geometry}
        material={materials.Bone}
        position={[0.163, 1.705, 1.894]}
      />
      <mesh
        name="Skull_cell049"
        geometry={nodes.Skull_cell049.geometry}
        material={materials.Bone}
        position={[1.625, -0.58, 0.717]}
      />
      <mesh
        name="Skull_cell050"
        geometry={nodes.Skull_cell050.geometry}
        material={materials.Bone}
        position={[-1.447, 0.235, 0.951]}
      />
      <mesh
        name="Skull_cell051"
        geometry={nodes.Skull_cell051.geometry}
        material={materials.Bone}
        position={[-1.732, 0.942, 1.31]}
      />
      <mesh
        name="Skull_cell054"
        geometry={nodes.Skull_cell054.geometry}
        material={materials.Bone}
        position={[1.067, -1.203, 1.415]}
      />
      <mesh
        name="Skull_cell055"
        geometry={nodes.Skull_cell055.geometry}
        material={materials.Bone}
        position={[1.173, 2.504, 0.03]}
      />
      <mesh
        name="Skull_cell056"
        geometry={nodes.Skull_cell056.geometry}
        material={materials.Bone}
        position={[-0.688, 1.057, 1.635]}
      />
      <mesh
        name="Skull_cell057"
        geometry={nodes.Skull_cell057.geometry}
        material={materials.Bone}
        position={[1.981, 0.115, 0.967]}
      />
      <mesh
        name="Skull_cell058"
        geometry={nodes.Skull_cell058.geometry}
        material={materials.Bone}
        position={[0.72, -1.631, 1.586]}
      />
      <mesh
        name="Skull_cell059"
        geometry={nodes.Skull_cell059.geometry}
        material={materials.Bone}
        position={[-1.55, 1.461, 0.165]}
      />
      <mesh
        name="Skull_cell060"
        geometry={nodes.Skull_cell060.geometry}
        material={materials.Bone}
        position={[1.21, 0.446, 1.03]}
      />
      <mesh
        name="Skull_cell062"
        geometry={nodes.Skull_cell062.geometry}
        material={materials.Bone}
        position={[1.736, 1.626, 0.986]}
      />
      <mesh
        name="Skull_cell063"
        geometry={nodes.Skull_cell063.geometry}
        material={materials.Bone}
        position={[-0.958, -1.724, 0.765]}
      />
      <mesh
        name="Skull_cell064"
        geometry={nodes.Skull_cell064.geometry}
        material={materials.Bone}
        position={[1.438, 1.566, -0.839]}
      />
      <mesh
        name="Skull_cell065"
        geometry={nodes.Skull_cell065.geometry}
        material={materials.Bone}
        position={[1.483, 1.548, -0.01]}
      />
      <mesh
        name="Skull_cell066"
        geometry={nodes.Skull_cell066.geometry}
        material={materials.Bone}
        position={[-0.028, -1.173, 1.1]}
      />
      <mesh
        name="Skull_cell067"
        geometry={nodes.Skull_cell067.geometry}
        material={materials.Bone}
        position={[0.359, -1.217, 1.915]}
      />
      <mesh
        name="Skull_cell069"
        geometry={nodes.Skull_cell069.geometry}
        material={materials.Bone}
        position={[-1.356, 2.228, 0.643]}
      />
      <mesh
        name="Skull_cell070"
        geometry={nodes.Skull_cell070.geometry}
        material={materials.Bone}
        position={[1.005, -1.282, 1.911]}
      />
      <mesh
        name="Skull_cell072"
        geometry={nodes.Skull_cell072.geometry}
        material={materials.Bone}
        position={[-0.696, -1.709, 1.944]}
      />
      <mesh
        name="Skull_cell073"
        geometry={nodes.Skull_cell073.geometry}
        material={materials.Bone}
        position={[0.004, 2.471, 0.594]}
      />
      <mesh
        name="Skull_cell074"
        geometry={nodes.Skull_cell074.geometry}
        material={materials.Bone}
        position={[-0.753, -0.005, -1.79]}
      />
      <mesh
        name="Skull_cell075"
        geometry={nodes.Skull_cell075.geometry}
        material={materials.Bone}
        position={[-1.059, -1.1, 1.408]}
      />
      <mesh
        name="Skull_cell076"
        geometry={nodes.Skull_cell076.geometry}
        material={materials.Bone}
        position={[0.738, -2.381, 1.732]}
      />
      <mesh
        name="Skull_cell077"
        geometry={nodes.Skull_cell077.geometry}
        material={materials.Bone}
        position={[-0.143, -0.405, 1.938]}
      />
      <mesh
        name="Skull_cell078"
        geometry={nodes.Skull_cell078.geometry}
        material={materials.Bone}
        position={[1.157, 1.246, -1.687]}
      />
      <mesh
        name="Skull_cell008"
        geometry={nodes.Skull_cell008.geometry}
        material={materials.Bone}
        position={[0.034, -1.84, 1.979]}
      />
      <mesh
        name="Skull_cell034"
        geometry={nodes.Skull_cell034.geometry}
        material={materials.Bone}
        position={[-0.402, -1.734, 1.708]}
      />
      <mesh
        name="Skull_cell052"
        geometry={nodes.Skull_cell052.geometry}
        material={materials.Bone}
        position={[-1.168, -1.863, 0.887]}
      />
      <mesh
        name="Skull_cell053"
        geometry={nodes.Skull_cell053.geometry}
        material={materials.Bone}
        position={[0.387, -1.8, 1.673]}
      />
      <mesh
        name="Skull_cell061"
        geometry={nodes.Skull_cell061.geometry}
        material={materials.Bone}
        position={[-0.966, -2.306, 1.202]}
      />
      <mesh
        name="Skull_cell068"
        geometry={nodes.Skull_cell068.geometry}
        material={materials.Bone}
        position={[0.947, -2.325, 1.194]}
      />
      <mesh
        name="Skull_cell071"
        geometry={nodes.Skull_cell071.geometry}
        material={materials.Bone}
        position={[-0.522, -1.02, 0.687]}
      />
      <mesh
        name="Skull_cell079"
        geometry={nodes.Skull_cell079.geometry}
        material={materials.Bone}
        position={[-0.77, -2.318, 1.804]}
      />
      <mesh
        name="Skull_cell080"
        geometry={nodes.Skull_cell080.geometry}
        material={materials.Bone}
        position={[0.671, -1.785, 2.001]}
      />
      <mesh
        name="origin"
        geometry={nodes.origin.geometry}
        material={materials.Bone}
        position={[0, 0.614, 0.076]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={826.146}
      />
    </group>
  );
}

useGLTF.preload("/models/skull.glb");
