/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/westernBlueBird.glb -o src/components/WesternBlueBird.jsx -r public -k 
Western bluebird by Poly by Google [CC-BY] (https://creativecommons.org/licenses/by/3.0/) via Poly Pizza (https://poly.pizza/m/cdcl5UwlYWd)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useControls } from "leva";
import { useExplode } from "../hooks/useExplode";

export function WesternBlueBird(props) {
  const { nodes, materials } = useGLTF("/models/westernBlueBird.glb");
  const group = useRef();

  const { bluebirddistance } = useControls({
    bluebirddistance: {
      value: 2.4,
      min: 0,
      max: 10,
    },
  });
  useExplode(group, {
    distance: bluebirddistance,
    rotationEnabled: true,
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="origin"
        geometry={nodes.origin.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.001, 1.389, 0.159]}
        scale={[2.885, 4.217, 4.217]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell002"
        geometry={nodes.WesternBluebird_Mesh_cell002.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.489, 0.43, 0.854]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell003"
        geometry={nodes.WesternBluebird_Mesh_cell003.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.007, 1.831, 2.081]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell004"
        geometry={nodes.WesternBluebird_Mesh_cell004.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.628, 0.968, -0.252]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell007"
        geometry={nodes.WesternBluebird_Mesh_cell007.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.174, -0.634, 0.641]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell009"
        geometry={nodes.WesternBluebird_Mesh_cell009.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.258, -0.074, -0.089]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell010"
        geometry={nodes.WesternBluebird_Mesh_cell010.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.246, -0.616, 0.006]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell011"
        geometry={nodes.WesternBluebird_Mesh_cell011.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.005, -0.018, -3.151]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell012"
        geometry={nodes.WesternBluebird_Mesh_cell012.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.538, 0.713, 1.191]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell013"
        geometry={nodes.WesternBluebird_Mesh_cell013.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.246, -0.371, 0.312]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell014"
        geometry={nodes.WesternBluebird_Mesh_cell014.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.068, 3.515, 2.182]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell015"
        geometry={nodes.WesternBluebird_Mesh_cell015.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.578, 0.488, -0.961]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell017"
        geometry={nodes.WesternBluebird_Mesh_cell017.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.04, 3.764, 1.957]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell018"
        geometry={nodes.WesternBluebird_Mesh_cell018.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.213, -0.627, 0.652]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell021"
        geometry={nodes.WesternBluebird_Mesh_cell021.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.068, 3.136, 1.971]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell023"
        geometry={nodes.WesternBluebird_Mesh_cell023.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.058, 0.335, 1.138]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell024"
        geometry={nodes.WesternBluebird_Mesh_cell024.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.409, 0.955, -1.395]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell026"
        geometry={nodes.WesternBluebird_Mesh_cell026.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.248, -0.618, -0.074]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell028"
        geometry={nodes.WesternBluebird_Mesh_cell028.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.266, -0.606, 0.838]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell029"
        geometry={nodes.WesternBluebird_Mesh_cell029.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.319, 0.337, -2.425]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell030"
        geometry={nodes.WesternBluebird_Mesh_cell030.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.722, 0.964, 0.148]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell031"
        geometry={nodes.WesternBluebird_Mesh_cell031.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.299, 0.17, -2.434]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell033"
        geometry={nodes.WesternBluebird_Mesh_cell033.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.124, 3.653, 1.774]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell034"
        geometry={nodes.WesternBluebird_Mesh_cell034.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.609, 1.294, 0.942]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell035"
        geometry={nodes.WesternBluebird_Mesh_cell035.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.458, 0.48, -0.058]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell036"
        geometry={nodes.WesternBluebird_Mesh_cell036.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.25, -0.611, -0.088]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell037"
        geometry={nodes.WesternBluebird_Mesh_cell037.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.513, 2.456, 1.521]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell041"
        geometry={nodes.WesternBluebird_Mesh_cell041.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.797, 1.755, -0.004]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell043"
        geometry={nodes.WesternBluebird_Mesh_cell043.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.242, 2.677, 1.821]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell044"
        geometry={nodes.WesternBluebird_Mesh_cell044.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.03, 0.174, -2.08]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell045"
        geometry={nodes.WesternBluebird_Mesh_cell045.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.011, 3.258, 2.406]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell046"
        geometry={nodes.WesternBluebird_Mesh_cell046.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.387, 2.853, 0.867]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell049"
        geometry={nodes.WesternBluebird_Mesh_cell049.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.322, 2.384, 1.821]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell050"
        geometry={nodes.WesternBluebird_Mesh_cell050.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.299, 3.22, 1.136]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell052"
        geometry={nodes.WesternBluebird_Mesh_cell052.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.059, 2.918, 2.398]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell053"
        geometry={nodes.WesternBluebird_Mesh_cell053.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.14, 1.814, -0.554]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell054"
        geometry={nodes.WesternBluebird_Mesh_cell054.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.252, -0.589, 0.607]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell055"
        geometry={nodes.WesternBluebird_Mesh_cell055.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.13, 3.348, 1.172]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell056"
        geometry={nodes.WesternBluebird_Mesh_cell056.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.375, 0.136, 0.462]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell057"
        geometry={nodes.WesternBluebird_Mesh_cell057.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.143, 0.168, 0.553]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell058"
        geometry={nodes.WesternBluebird_Mesh_cell058.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.001, 3.171, 0.665]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell059"
        geometry={nodes.WesternBluebird_Mesh_cell059.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.152, -0.618, 0.949]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell061"
        geometry={nodes.WesternBluebird_Mesh_cell061.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.609, 2.223, 0.827]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell063"
        geometry={nodes.WesternBluebird_Mesh_cell063.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.098, 2.27, 2.021]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell064"
        geometry={nodes.WesternBluebird_Mesh_cell064.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.363, 2.17, 1.071]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell065"
        geometry={nodes.WesternBluebird_Mesh_cell065.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.259, -0.518, 0.367]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell066"
        geometry={nodes.WesternBluebird_Mesh_cell066.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.133, 3.026, 2.565]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell067"
        geometry={nodes.WesternBluebird_Mesh_cell067.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.145, 0.571, -2.362]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell068"
        geometry={nodes.WesternBluebird_Mesh_cell068.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.082, 1.415, 1.737]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell069"
        geometry={nodes.WesternBluebird_Mesh_cell069.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.483, 2.129, 0.134]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell070"
        geometry={nodes.WesternBluebird_Mesh_cell070.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.173, -0.607, 0.785]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell071"
        geometry={nodes.WesternBluebird_Mesh_cell071.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.733, 0.717, 0.749]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell072"
        geometry={nodes.WesternBluebird_Mesh_cell072.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.253, -0.608, 0.094]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell073"
        geometry={nodes.WesternBluebird_Mesh_cell073.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.22, -0.013, -0.028]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell074"
        geometry={nodes.WesternBluebird_Mesh_cell074.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.399, 2.992, 1.396]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell075"
        geometry={nodes.WesternBluebird_Mesh_cell075.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.545, 0.91, -1.477]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell077"
        geometry={nodes.WesternBluebird_Mesh_cell077.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.007, -0.222, -3.535]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell078"
        geometry={nodes.WesternBluebird_Mesh_cell078.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.611, 1.614, 1.146]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell080"
        geometry={nodes.WesternBluebird_Mesh_cell080.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.303, 3.299, 1.676]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell081"
        geometry={nodes.WesternBluebird_Mesh_cell081.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.233, 0.78, 1.172]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell083"
        geometry={nodes.WesternBluebird_Mesh_cell083.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.268, 2.526, 0.533]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell084"
        geometry={nodes.WesternBluebird_Mesh_cell084.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0, 2.924, 2.925]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell085"
        geometry={nodes.WesternBluebird_Mesh_cell085.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.222, 0.25, -0.926]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell086"
        geometry={nodes.WesternBluebird_Mesh_cell086.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.089, 0.314, -1.635]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell001"
        geometry={nodes.WesternBluebird_Mesh_cell001.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.354, -0.603, 0.791]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell005"
        geometry={nodes.WesternBluebird_Mesh_cell005.geometry}
        material={materials.WesternBluebird_Mat}
        position={[-0.163, -0.606, 0.881]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell006"
        geometry={nodes.WesternBluebird_Mesh_cell006.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.27, -0.625, 1.016]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell008"
        geometry={nodes.WesternBluebird_Mesh_cell008.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.154, -0.619, 0.96]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell016"
        geometry={nodes.WesternBluebird_Mesh_cell016.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.267, -0.601, 0.813]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell019"
        geometry={nodes.WesternBluebird_Mesh_cell019.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.349, -0.599, 0.779]}
      />
      <mesh
        name="WesternBluebird_Mesh_cell020"
        geometry={nodes.WesternBluebird_Mesh_cell020.geometry}
        material={materials.WesternBluebird_Mat}
        position={[0.245, -0.591, -0.039]}
      />
    </group>
  );
}

useGLTF.preload("/models/westernBlueBird.glb");
